config/routes.rb
Rails.application.routes.draw do

  resources :posts, except: [:index] do 
    member do 
      put "like", to: "posts#like"
      put "unlike", to: "posts#unlike"
    end
  end
  resources :comments, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  devise_for :users 
  resources :users, only: [:show] do 
    member do 
      get :following, :followers
    end
  end
  

  root 'static_pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
  acts_as_commentable
  mount_uploader :image, ImageUploader
	# has_attached_file :image, styles: { medium: "640x640#" }, default_url: "/images/:style/missing.png"
 #  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base  
  mount_uploader :profile_picture, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts  
  # has_attached_file :profile_picture, styles: { medium: "300x300>" }, default_url: "missing_user.jpg"
  # validates_attachment_content_type :profile_picture, content_type: /\Aimage\/.*\Z/
  acts_as_voter
  has_many :active_relationships, class_name: "Relationship",
  																foreign_key: "follower_id",
  																dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
  																 foreign_key: "followed_id",
  																 dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  def follow(other_user)
  	active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
  	active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
  	following.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected 
  def configure_permitted_parameters 
  	devise_parameter_sanitizer.permit(:account_update) do |user_params|
  		user_params.permit(:username, :biography, :email, :password,
      :password_confirmation, :current_password, :profile_picture)
  	end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)
		@comment.user_id = params[:user_id]
		@comment.save
		respond_to do |format|
			format.html { redirect_to root_url }
			format.js
		end
	end

	def destroy		
		@comment = Comment.find(params[:id])
		@post = Post.find(@comment.commentable_id) # post_id for AJAX response
		@comment.destroy
		respond_to do |format|
			format.html { redirect_to root_url }
			format.js
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:comment)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like
    @post.liked_by current_user 
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def unlike
    @post.unliked_by current_user
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:caption, :image)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_action :authenticate_user!

	def create
		@user = User.find(params[:followed_id])
		current_user.follow(@user)
		respond_to do |format|
			format.html { redirect_to @user }
			format.js
		end
	end

	def destroy
		@user = Relationship.find(params[:id]).followed 
		current_user.unfollow(@user)
		respond_to do |format|
			format.html { redirect_to @user }
			format.js 
		end
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home  	
	  @posts = []
  	if current_user
	  	@posts = Post.where("user_id IN (?) OR user_id = ?", current_user.following_ids, current_user.id)
	  	@posts = @posts.order('created_at DESC')
	  end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user

	def show 
		@posts = @user.posts.order("created_at DESC")
	end

	def followers
		@users = @user.followers
		if @users.empty?
			redirect_to @user
		else 
			render 'show_follow'
		end
	end

	def following
		@users = @user.following
		if @users.empty?
			redirect_to @user
		else 			
			render 'show_follow'
		end
	end

	private 
	def set_user 
		@user = User.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def time_ago(time)
		string = time_ago_in_words(time)
		return "1m" if string !~ /\d/
		string = string.split(" ")
		string.shift if string[0] !~ /\d/
		string = string[0] + string[1][0]
		return string
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<% post.comments.recent.each do |comment| %>
	<p>
		<%= link_to comment.user do %>
			<strong><%= comment.user.username %></strong>
		<% end %>
		<span class = "comment"><%= comment.comment %></span>
		<% if comment.user_id == current_user.id || post.user_id == current_user.id %>
		<%= render partial: 'comments/destroy', object: comment, as: 'comment' %>		
		<% end %>
	</p>
<% end %>

app/views/comments/_create.html.erb
<%= form_for(post.comments.build, remote: true) do |f| %>
	<%= hidden_field_tag :user_id, current_user.id %>
	<%= hidden_field_tag :post_id, post.id %>
  <div class="field">
    <%= f.text_field :comment, class: "comment_input", placeholder: "Add a comment..." %>
  </div>
<% end %>

app/views/comments/_destroy.html.erb
<%= link_to comment, class: 'delete', method: :delete, remote: true, data: { confirm: "Are you sure?"} do %>
<% end %>

app/views/comments/create.js.erb
$("#comment_section_<%= @post.id %>").html("<%= j render partial: 'comments', object: @post, as: 'post' %>")
$("#user_action_<%= @post.id %>").find("#new_comment")[0].reset()

app/views/comments/destroy.js.erb
$("#comment_section_<%= @post.id %>").html("<%= j render partial: 'comments', object: @post, as: 'post' %>")

app/views/layouts/_navigation.html.erb
<% if current_user %>
	<nav class = "navbar navbar-default">
		<div class = "nav-container">	
			<div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to 'Instagram-Clone'.html_safe, root_url, class: "navbar-brand" %>
    	</div>
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">			
				<ul class = "nav navbar-nav navbar-right">
					<li><%= link_to '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>'.html_safe, new_post_path %></li>
					<li><%= link_to '<span class="glyphicon glyphicon-user" aria-hidden="true"></span>'.html_safe, user_path(current_user) %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure?"} %></li>
				</ul>			
			</div>
		</div>
	</nav>	
<% else %>
<br/><br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<%= render "layouts/navigation" %>
	<div class = "container <%= controller.controller_name %>">
		<%= render 'shared/flash_message' %>
		<%= yield %>
	</div>

</body>
</html>

app/views/posts/_feed_post.html.erb
<div class = "post">
	<%= render partial: 'shared/user_basic_info', object: post.user, as: 'user', locals: { time: post.created_at } %>
	<div class = "image" id = "target_<%= post.id %>">
		<div class = "like hide"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></div>
		<%= image_tag(post.image.url(:thumb)) %>
	</div>
	<div class = "post_details">
		<p><strong id = "post_<%= post.id %>"><%= pluralize(post.votes_for.size, "like") %></strong></p>
		<% if !post.caption.empty? %>
			<p><strong><%= post.user.username %></strong> <%= post.caption %></p>
		<% end %>
		<div id = "comment_section_<%= post.id %>">
			<% if post.comments.any? %>
				<%= render partial: 'comments/comments', object: post, as: 'post' %>
			<% end %>
		</div>
		<div id = "user_action_<%= post.id %>">
			<span id = "like_button_<%= post.id %>">
				<% if current_user.voted_for? post %>
					<%= render partial: 'posts/unlike', object: post, as: 'post' %>
				<% else %>
					<%= render partial: 'posts/like', object: post, as: 'post' %>
				<% end %>
			</span>			
			<%= render partial: 'comments/create', object: post, as: 'post' %>
		</div>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { multipart: true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_area :caption, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Share", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_like.html.erb
<%= link_to like_post_path(post), remote: true, method: :put do %>
	<span class="glyphicon glyphicon-heart unliked" aria-hidden="true">
<% end %>			

app/views/posts/_post.html.erb
<% if controller.controller_name == "static_pages" %>
	<%= render partial: 'posts/feed_post', object: post, as: 'post' %>
<% else %>
	<%= render partial: 'posts/user_post', object: post, as: 'post' %>
<% end %>
	

app/views/posts/_unlike.html.erb
<%= link_to unlike_post_path(post), remote: true, method: :put do %>
	<span class="glyphicon glyphicon-heart liked" aria-hidden="true">
<% end %>			

app/views/posts/_user_post.html.erb
<div class = "post">
	<div class = "image left" id = "target_<%= post.id %>">
		<div class = "like hide"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></div>
		<%= image_tag(post.image.url(:thumb)) %>
	</div>
	<div class = "right">
		<%= render partial: 'shared/user_basic_info', object: post.user, as: 'user', locals: { time: post.created_at } %>
		<hr/>
		<div class = "post_details">
			<p><strong id = "post_<%= post.id %>"><%= pluralize(post.votes_for.size, "like") %></strong></p>
			<% if !post.caption.empty? %>
				<p><strong><%= post.user.username %></strong> <%= post.caption %></p>
			<% end %>
			<div id = "comment_section_<%= post.id %>">
				<% if post.comments.any? %>
					<%= render partial: 'comments/comments', object: post, as: 'post' %>
				<% end %>
			</div>
			
		</div>
	</div>
	<div id = "user_action_<%= post.id %>">
				<span id = "like_button_<%= post.id %>">
					<% if current_user.voted_for? post %>
						<%= render partial: 'posts/unlike', object: post, as: 'post' %>
					<% else %>
						<%= render partial: 'posts/like', object: post, as: 'post' %>
					<% end %>
				</span>			
				<%= render partial: 'comments/create', object: post, as: 'post' %>
			</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/like.js.erb
$("#post_<%= @post.id %>").html("<%= pluralize(@post.votes_for.size, "like") %>")
$("#like_button_<%= @post.id %>").html("<%= j render partial: 'posts/unlike', object: @post, as: 'post' %>")

app/views/posts/new.html.erb
<div class = "box_container col-md-6 col-md-offset-3">
	<h2 class = "text-center">New Post</h1>
	<%= render 'form' %>
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class = "col-xs-10 col-xs-offset-1">
	<%= render @post %>
</div>

app/views/posts/unlike.js.erb
$("#post_<%= @post.id %>").html("<%= pluralize(@post.votes_for.size, "like") %>")
$("#like_button_<%= @post.id %>").html("<%= j render partial: 'posts/like', object: @post, as: 'post' %>")

app/views/relationships/create.js.erb
$('#follow_form_<%= @user.id %>').html("<%= j render('users/unfollow', user: @user) %>");
$('#followers').html("<%= @user.followers.count %>")

app/views/relationships/destroy.js.erb
$('#follow_form_<%= @user.id %>').html("<%= j render('users/follow', user: @user) %>");
$('#followers').html("<%= @user.followers.count %>")

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
	<div class = "alert  alert-success">
		<%= value %>
	</div>
<% end %>

app/views/shared/_user_basic_info.html.erb
<div class = "user_basic_info">
	<div class = "profile_picture">
		<%= image_tag(user.profile_picture.url) %>
	</div>
	<div class = "details">
		<p><%= user.username %></p>
	</div>
	<% if time %>
		<div class = "time"><%= time_ago(time) %></div>
	<% else %>
		<%= render 'users/follow_form', user: user %>
	<% end %>
</div>

app/views/static_pages/_landing.html.erb
<div class = "col-md-6 col-md-offset-3">	
	<div class = "box_container">

		<h1 class = "text-center">Instagram-Clone</h1>
		<div class = "row">
			<div class = "col-md-6 home">
				<%= image_tag("home_page.png") %>
			</div>

			<div class = "col-md-6 sign-up">
				<p class = 'text-center'>Sign Up to see photos and videos from your friends</p>
				<br/>
				<%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary center-block' %>
				<hr/>
				<p class = "text-center">Have an account? <%= link_to 'Log in', new_user_session_path %></p>
			</div>
		</div>

	</div>
</div>

app/views/static_pages/home.html.erb
<% if !@posts.empty? %>
	<div class = "feeds col-xs-6 col-xs-offset-3">
		<%= render @posts %>
	</div>
<% else %>	
	<% if user_signed_in? %>
		No Feeds Available Yet.
	<% else %>
		<%= render 'landing' %>
	<% end %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if user_signed_in? %>
	<div id = "follow_form_<%= user.id %>">
		<% if current_user.following?(user) %>
			<%= render 'unfollow', user: user %>
		<% else %> 
			<%= render 'follow', user: user %>
		<% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-default" %>
<% end %>

app/views/users/show.html.erb
<div class = "user col-md-8 col-md-offset-2">
	<div class = "profile_picture">
		<%= image_tag(@user.profile_picture.url) %>
	</div>
	<div class = "details">
		<h3><%= @user.username %></h3>
		<% if current_user == @user %>
			<%= link_to "Edit Profile", edit_user_registration_path, class: 'btn btn-default edit' %>
		<% else %>
			<%= render 'follow_form', user: @user %>
		<% end %>
		<p><%= @user.biography %></p>	
		<ul>
			<li><strong><%= @user.posts.size %></strong> posts </li>
			<li><a href = "<%= following_user_path(@user) %>"><strong id = "following"><%= @user.following.count %></strong> following</a></li>
			<li><a href = "<%= followers_user_path(@user) %>"><strong id = "followers"><%= @user.followers.count %></strong> followers</a></li>
		</ul>
	</div>
</div>
<div class = "posts">
	<% @posts.each do |post| %>
		<%= link_to post do %>
			<div class = "col-xs-4">
					<div class = "post">
					<%= image_tag(post.image.url(:thumb)) %>
					<div class = "bg-features">	
						<div class = "features">
							<div class = "likes">
								<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
								<%= post.votes_for.size %>
							</div>
							<div class = "comments">
								<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
								0
							</div>
						</div>
					</div>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

app/views/users/show_follow.html.erb
<div class = "box_container col-xs-6 col-xs-offset-3">
	<% @users.each do |user| %>
	<%= render partial: 'shared/user_basic_info', object: user, as: 'user', locals: { time: nil } %>
	<% end %>
</div>